name: 'CI/CD'
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16' # Specify Node.js version

      - name: Install and Run Linter
        run: |
          # Initialize npm and install the necessary ESLint dependencies
          npm init -y
          npm install eslint eslint-config-standard eslint-plugin-import eslint-plugin-n eslint-plugin-promise

          # Find and lint all specified JavaScript files
          find ./secondChance-backend -name app.js -exec ./node_modules/.bin/eslint -c .eslintrc.js {} +
          find ./secondChance-backend -name auth.js -exec ./node_modules/.bin/eslint -c .eslintrc.js {} +
          find ./secondChance-backend -name secondChanceItemsRoutes.js -exec ./node_modules/.bin/eslint -c .eslintrc.js {} +
          find ./secondChance-backend -name searchRoutes.js -exec ./node_modules/.bin/eslint -c .eslintrc.js {} +
          find ./secondChance-backend -name index.js -exec ./node_modules/.bin/eslint -c .eslintrc.js {} +
          find ./sentiment -name index.js -exec ./node_modules/.bin/eslint -c .eslintrc.js {} +
          
          echo "Linted all the js files successfully"
